services:
  - type: web
    runtime: docker
    name: tweeter-api
    dockerCommand: ./api
    plan: free
    envVars:
      - key: ConnectionStrings
        value: Server=db;Database=tweeter;User Id=sa;Password=1q1q1q1q!Q!Q!Q!Q;MultipleActiveResultSets=true;TrustServerCertificate=true

  - type: web
    runtime: docker
    plan: free
    name: tweeter-web
    dockerCommand: ./web

  - type: pserv
    name: tweeter-db
    env: docker
    plan: free
    dockerCommand: ./db
    envVars:
      - fromGroup: mysql

envVarGroups:
  - name: mysql
    envVars:
      - key: SA_PASSWORD
        value: "1q1q1q1q!Q!Q!Q!Q"
      - key: ACCEPT_EULA
        value: "Y"
